name: Generate json index & ReadMe

on:
  push:
    branches:
      - main
    paths:
      - "javascript/**"
      - "anime_index.json"
      - "scripts/anime_metadata.json"
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "America/New_York"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install modules
        run: |
          pip install -r requirements.txt

      - name: Update extensions
        run: |
          python scripts/generator_source.py

      - name: Update ReadMe
        run: |
          python scripts/generator_readme.py

      - name: Commit and Push Changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git diff --staged --quiet && echo "Nothing to commit" || (git commit -m "[bot] Update README and index" && git push)
